# Documentation
# https://docs.docker.com/compose/compose-file

version: '3'

services:
  sonarqube:
        container_name:  sonarqube
        image:  sonarqube:latest
        ports:
            -  "9000:9000"
            -  "9092:9092"

networks:
  backend:
    driver: bridge
